### ISSUE TITLE
Provide a Python binding for PPMP

### ISSUE THREAD

**Issue by kartben** [eclipse/unide#10]
It would be useful to have a Python library that people can use to serialize/unserialize PPMP objects.

**Comment by kartben** [comment]
something for @fpatz, maybe 😊

**Comment by fpatz** [comment]
Yes, indeed. We are working on that.

**Comment by fpatz** [comment]
Thanks, @kartben for bringing this up here. I wonder how the Unide team looks at this. Should a Python library for PPMP live here or in a separate project? It would be useful to publish a Python library using the standard channels like PyPI, which suggests a separate project, at least a separate repo etc.

**Comment by kartben** [comment]
I briefly spoke with @muelsen this morning so I will let him correct me if I'm wrong. I think the Eclipse Unide team would be happy to have the code hosted on the "official" Unide repo - *distributing* through PyPi certainly sounds like a good idea.

**Comment by fpatz** [comment]
I'd be ok with that if we find ways to handle the tooling issues:

- we'd have tightly coupled release life cycles, even for e.g. bugfix releases
- AFAIK, it is not easy to use Travis CI (or other CI/automation services) with multiple languages/subprojects in one Github repo
- top-level Maven would also have to drive the Python project automation or be moved down into the Java subproject

That's just what comes off the top of my head right now. The problems will only become harder when more programming language bindings start to appear. I'd assume, that one repo for each supported language will be easier to maintain long-term. The project page at eclipse.org could link to all those projects, and the repos can link back to the project page.

OTOH, there may be also pros: we can share test data, and interoperability testing with the server may be easier.

**Comment by ameinhardt** [comment]
seems like the contribution questionnaire [has been approved](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14478), but there is [no progress on creating seperate repos for the bindings](https://bugs.eclipse.org/bugs/show_bug.cgi?id=525920). @kartben, any advice?
