### ISSUE TITLE
[website] PPMP specification reference commercial product

### ISSUE THREAD

**Issue by kartben** [eclipse/unide#13]
In https://www.eclipse.org/unide/specification/, the doc for "operationStatus" attribute of Process payload says:

```
The operationalStatus describes the status of a device. It is a string matching a definition in the Production Performance Manager.
```

Please fix so that the doc (and PPMP itself) does not require on commercial solutions.

**Comment by ameinhardt** [comment]
Hi @kartben,
this should be resolved with [commit 72196cb2148f3d024639ac7629ef972ae7c8a1d2](https://git.eclipse.org/r/plugins/gitiles/www.eclipse.org/unide/+/72196cb2148f3d024639ac7629ef972ae7c8a1d2). Unfortunately, I cannot edit this issue in github (yet?!).
