### ISSUE TITLE
Online Validation - Meassurement: difference between spec and validation service: meassurements or messages ?

### ISSUE THREAD

**Issue by jwende** [eclipse/unide#16]
Invoking the validation service with a meassuremtns message returns the following error: 
"meassurements":"is not defined in the schema and the schema does not allow additional properties","messages":"is missing but it is required"

**Comment by jwende** [comment]
Double check my environment first

**Comment by jwende** [comment]
The reason for this error message was:
- endpoint used for validating meassurement messages (https://unide.eclipse.org/rest/v2/measurement?validate=true)
- content-spec set for machine-messages  (urn:spec://eclipse.org/unide/machine-message#v2)

Re-opening the issue as I would expect other error messages if using the wrong endpoint.

Cheers
J.

**Comment by ameinhardt** [comment]
good suggestion. I'll have a look at that for the next release

**Comment by ameinhardt** [comment]
in the recently committed code, there a seperate validation endpoint now:
/rest/v2/validate. The message is determined by the content-spec. See:
[documentation - REST Endpoints](https://github.com/eclipse/unide/blob/d0cba44ac7528df58ffc2632e8daa1684901373c/servers/rest/src/main/docs/asciidoc/documentation.adoc#rest-endpoints)
