### ISSUE TITLE
What is normative ?

### ISSUE THREAD

**Issue by jwende** [eclipse/unide#18]
Just wondering - what is the normative reference for Unide ?
- the spec on the eclipse web side (https://www.eclipse.org/unide/proposal/)
or
- the validation service and the embedded json schema files ?

Thanks for clarification 
J.

**Comment by ameinhardt** [comment]
Hi @jwende ,
both should be in sync. If you find deviations, let me now, so we can make sure they are aligned.

**Comment by ameinhardt** [comment]
The validation service uses json schema. The website specification is now also generated from these very json schema files.
I'm still looking for a way to enforce that two arrays should have the same length. Unfortunately, json-schema or json-path are not powerful enough, in my opinion.
