### ISSUE TITLE
REST Server db index

### ISSUE THREAD

**Issue by ameinhardt** [eclipse/unide#20]
In order to save measurements with identical deviceId and timestamp but different device property names, add such tag()
https://github.com/eclipse/unide/blob/2a12a7b94215ac795c7222cc82671e476eb69cba/servers/rest/src/main/java/server/persistency/dao/MeasurementDAO.java#L102-L103

also for process shutoffvalues:
https://github.com/eclipse/unide/blob/2a12a7b94215ac795c7222cc82671e476eb69cba/servers/rest/src/main/java/server/persistency/dao/ProcessDAO.java#L182-L186
and special values:
https://github.com/eclipse/unide/blob/2a12a7b94215ac795c7222cc82671e476eb69cba/servers/rest/src/main/java/server/persistency/dao/ProcessDAO.java#L229-L232

if measurements() always hold the deviceId, do we need another tag deviceId?
in [ProcessDao](https://github.com/eclipse/unide/blob/eec10c6d75a374df84a598f73d0321c5e9d004f4/servers/rest/src/main/java/server/persistency/dao/ProcessDAO.java#L368), [MachineMessageDao](https://github.com/eclipse/unide/blob/eec10c6d75a374df84a598f73d0321c5e9d004f4/servers/rest/src/main/java/server/persistency/dao/MachineMessageDAO.java#L111) and [MeasurementDao](https://github.com/eclipse/unide/blob/2a12a7b94215ac795c7222cc82671e476eb69cba/servers/rest/src/main/java/server/persistency/dao/MeasurementDAO.java#L166)

**Comment by davidgs** [comment]
The Device ID should not be the Measurement, but a Tag on the measurement.

**Comment by ameinhardt** [comment]
@davidgs: thanks, that's how we did it now!
The *DAOs are now called [*Comsumer](https://github.com/eclipse/unide/tree/master/servers/rest/src/main/java/server/receiver/influxdb).
The documentation for the influx mapping has been documented in [documentation - InfluxDB Schema Design](https://github.com/eclipse/unide/blob/master/servers/rest/src/main/docs/asciidoc/documentation.adoc#influxdb-schema-design)
Example:
https://github.com/eclipse/unide/blob/d0cba44ac7528df58ffc2632e8daa1684901373c/servers/rest/src/main/java/server/receiver/influxdb/MachineMessageConsumer.java#L50-L53
