### ISSUE TITLE
Release artifacts location

### ISSUE THREAD

**Issue by sophokles73** [eclipse/unide#22]
Hi,
I have seen that you have created an 0.1.0 release. I haven't been able to find the artifacts on Maven Central, though. Is this intentional, i.e. are you not planning to make the artifacts available from there?
If so, is there another Maven repository that I can get the artifacts from?

**Comment by ameinhardt** [comment]
Please find the current snapshot here: https://repo.eclipse.org/content/repositories/unide-snapshots/
and the (future) releases here: https://repo.eclipse.org/content/repositories/unide-releases/
