### ISSUE TITLE
Cannot Install/Compile Client nor website with npm install

### ISSUE THREAD

**Issue by VolITSol** [eclipse/unide#27]
Hi,

Tried do install client and website but get this error... Using Win 10 and Powershell...
Is this a Win-Problem? 

Thanks a lot for any help!!!

PS C:\development\unide\website> npm version
{ unide: '1.0.0',
  npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.11.4',
  openssl: '1.0.2l',
  uv: '1.11.0',
  v8: '5.1.281.108',
  zlib: '1.2.11' }

PS C:\development\unide\website> npm install

[npm-debug.log](https://github.com/eclipse/unide/files/1694304/npm-debug.log)
> unide@1.0.0 postinstall C:\development\unide\website
> npm run generate

> unide@1.0.0 generate C:\development\unide\website
> nuxt generate

C:\development\unide\website\node_modules\nuxt\lib\core\module.js:14
  async ready() {
        ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\development\unide\website\node_modules\nuxt\lib\core\index.js:2:16)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\development\\nodejs\\node.exe" "C:\\development\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "generate"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! unide@1.0.0 generate: `nuxt generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unide@1.0.0 generate script 'nuxt generate'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the unide package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nuxt generate
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs unide
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls unide
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\development\unide\website\npm-debug.log

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\watchpack\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN eslint-config-vue@2.0.2 requires a peer of eslint@^2.0.0 || ^3.0.0 but none was installed.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\development\\nodejs\\node.exe" "C:\\development\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! unide@1.0.0 postinstall: `npm run generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unide@1.0.0 postinstall script 'npm run generate'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the unide package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run generate
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs unide
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls unide
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\development\unide\website\npm-debug.log

**Comment by he99** [comment]
Maybe [nuxt issue #6212](https://github.com/nuxt/nuxt.js/issues/2612)?

**Comment by ameinhardt** [comment]
Sorry for the late reply, @VolITSol.
I think async/await was introduced with node.js 7.6 or so. Therefore, Nuxt.js requires [>=8](https://github.com/nuxt/nuxt.js/blob/a6b8fe565a168784dd851c1299d5e9725cca0f97/package.json#L56) and the [html5 client as well](https://github.com/eclipse/unide/blob/be901263d95bb82a75f0f4fa73de1d123f78d907/clients/binsa/package.json#L104).
If you upgrade your node.js, do you still get the problem?
