### ISSUE TITLE
ppmp-server: Could not resolve dependencies

### ISSUE THREAD

**Issue by davidgs** [eclipse/unide#31]
Trying to install and run the united server on Mac OS X ... 

`[INFO] Building unide-server 0.2.0-SNAPSHOT`
`[INFO] ------------------------------------------------------------------------`
`[WARNING] The POM for org.eclipse.iot.unide.ppmp:ppmp-java-binding:jar:0.2.0-SNAPSHOT is missing, no dependency information available`
`[INFO] ------------------------------------------------------------------------`
`[INFO] Reactor Summary:`
`[INFO]`
`[INFO] ppmp-schema ........................................ SUCCESS [  1.843 s]`
`[INFO] Unide .............................................. SUCCESS [  0.027 s]`
`[INFO] unide-servers ...................................... SUCCESS [  0.023 s]`
`[INFO] unide-server ....................................... FAILURE [  0.844 s]`
`[INFO] ------------------------------------------------------------------------`
`[INFO] BUILD FAILURE`
`[INFO] ------------------------------------------------------------------------`
`[INFO] Total time: 2.939 s`
`[INFO] Finished at: 2018-03-08T17:14:40-05:00`
`[INFO] Final Memory: 13M/245M`
`[INFO] ------------------------------------------------------------------------`
`[ERROR] Failed to execute goal on project ppmp-server: Could not resolve dependencies for project org.eclipse.iot.unide.ppmp:ppmp-server:jar:0.2.0-SNAPSHOT: Could not find artifact org.eclipse.iot.unide.ppmp:ppmp-java-binding:jar:0.2.0-SNAPSHOT -> [Help 1]`
`[ERROR]`
`[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.`
`[ERROR] Re-run Maven using the -X switch to enable full debug logging.`
`[ERROR]`
`[ERROR] For more information about the errors and possible solutions, please read the following articles:`
`[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`
`[ERROR]`
`[ERROR] After correcting the problems, you can resume the build with the command`
`[ERROR]   mvn <goals> -rf :ppmp-server`

**Comment by ameinhardt** [comment]
Hi David,

If you git clone and mvn install the java binding first:
https://github.com/eclipse/unide.java
Does it work after?

Mit freundlichen Grüßen / Best regards

Axel Meinhardt

(BCI/ECM2, Technical Lead Ecosystem)
Bosch Software Innovations GmbH | Ullsteinstr. 128 | 12109 Berlin | GERMANY | www.bosch-si.com<http://www.bosch-si.com>
Tel. +49 30 726112486 | Mobil +49 173 5173094 | Fax +49 30 726112-100 | axel.meinhardt@bosch-si.com<mailto:axel.meinhardt@bosch-si.com>

Sitz: Berlin, Registergericht: Amtsgericht Charlottenburg; HRB 148411 B
Aufsichtsratsvorsitzender: Dr.-Ing. Thorsten Lücke; Geschäftsführung: Dr. Stefan Ferber, Michael Hahn

**Comment by davidgs** [comment]
Sadly, no. 
`[INFO] ------------------------------------------------------------------------`
`[INFO] Reactor Summary:`
[org.eclipse.iot.unide.server.jdbc.JdbcMockFactoryTest.txt](https://github.com/eclipse/unide/files/1797023/org.eclipse.iot.unide.server.jdbc.JdbcMockFactoryTest.txt)
[org.eclipse.iot.unide.server.web.RestEndpointPostgresTest.txt](https://github.com/eclipse/unide/files/1797024/org.eclipse.iot.unide.server.web.RestEndpointPostgresTest.txt)
[org.eclipse.iot.unide.server.web.RestEndpointValidationTest.txt](https://github.com/eclipse/unide/files/1797025/org.eclipse.iot.unide.server.web.RestEndpointValidationTest.txt)
[org.eclipse.iot.unide.server.web.RestEndpointInfluxTest.txt](https://github.com/eclipse/unide/files/1797026/org.eclipse.iot.unide.server.web.RestEndpointInfluxTest.txt)




`[INFO]`
`[INFO] unide-servers ...................................... SUCCESS [  0.429 s]`
`[INFO] unide-server ....................................... FAILURE [ 42.398 s]`
`[INFO] ------------------------------------------------------------------------`
`[INFO] BUILD FAILURE`
`[INFO] ------------------------------------------------------------------------`
`[INFO] Total time: 43.121 s`
`[INFO] Finished at: 2018-03-09T08:28:03-05:00`
`[INFO] Final Memory: 90M/702M`
`[INFO] ------------------------------------------------------------------------
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project ppmp-server: There are test failures.`
`[ERROR]`
`[ERROR] Please refer to /Users/davidgs/EclipseIoT/unide/servers/rest/target/surefire-reports for the individual test results.`
`[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project ppmp-server: There are test failures.`

**Comment by ameinhardt** [comment]
Hi @davidgs,
sorry for the inconvenience! Before, I had problems with the tests on the eclipse jenkins because of timezone issues. It's hard to tell if that happens here again, based on the infos.
For your purpose, you might also want to just use an automatic build directly from the [eclipse repo](https://repo.eclipse.org/#nexus-search;quick~ppmp-server)  like [ppmp-server-0.2.0-20180315.235004-19.jar](https://repo.eclipse.org/service/local/repositories/unide-snapshots/content/org/eclipse/iot/unide/ppmp/ppmp-server/0.2.0-SNAPSHOT/ppmp-server-0.2.0-20180315.235004-19.jar) and start it with an [appropriate configuration](https://github.com/eclipse/unide/blob/master/servers/rest/src/main/docs/asciidoc/documentation.adoc#configuration).

**Comment by ameinhardt** [comment]
Hi @davidgs ,
I added a description on how to quickly get started with the REST Server here:
https://github.com/eclipse/unide/blob/master/website/blog/Release-0.2.0.md

Also I saw from your logs:
```
java.lang.RuntimeException: No stub for url: 'http://localhost:8080/sqlStub' body: '<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.13.9</center>
```
It seems that there's an nginx running on that port, so the tests possibly can't spawn the test interface.

**Comment by kartben** [comment]
> It seems that there's an nginx running on that port, so the tests possibly can't spawn the test interface.

It is probably not so uncommon to have services running on the build machine on port 8080 - maybe worth updating the tests to use a random port and/or try 8081, 8082, etc. automatically?
