### ISSUE TITLE
Unable to read data from persistance DB

### ISSUE THREAD

**Issue by karthigaChell** [eclipse/unide#32]
Hi, 
I have downloaded and installed  master(0661bbc) on windows 7. 
I have configured "persistence.system" : "InfluxDB". When I run ppmp server, the databases Messages, Measurements and Processes were created in Influxdb. But ppmp_messages,  ppmp_measurements and ppmp_processes tables were not created by ppmp server.

Thanks, 
Karthiga Rajendran

**Comment by ameinhardt** [comment]
Hi @karthigaChell,
I can not reproduce that based on your information. Can you try version 0.2.0 of the REST server [as described in the blog entry](https://github.com/eclipse/unide/blob/master/website/blog/Release-0.2.0.md) and trace the (http-) communication from REST Server to influxDB?
