### ISSUE TITLE
Result should be an enum?

### ISSUE THREAD

**Issue by kartben** [eclipse/unide#6]
In Measurement and Process schemas, 'result' is defined as a simple string, whereas the spec says it's an enum { OK, NOK, UNKNOWN }

Therefore it should be defined as follows in the JSON schemas:
``` 
 "result": {
    "enum": [ "OK", "NOK", "UNKNOWN" ]
  },
```

**Comment by muelsen** [comment]
FIXED: d02d50f86758993b6c56bc4e9ac47ea56d873ff9
