### ISSUE TITLE
Should unit tests validate test JSON files against schemas?

### ISSUE THREAD

**Issue by kartben** [eclipse/unide#9]
The "measurement.json" file is not valid as per the json schema (i.e force and pressure measurements series do not have the $_time field set), which is very confusing since, well, it sounds like it is a reference document :-) Trying to POST it to the HTTP endpoint will fail with following error if validation is enabled:
```
{
    "measurements[1].series.$_time": "is missing but it is required"
}
```

This issue might need to be splitted in several as you see fit:
* the measurement.json test file should certainly be valid as per the schema
* maybe part of each unit test should be a @Test that performs a JSON Schema validation?

**Comment by ameinhardt** [comment]
with suggested fixes in #21, also process.json needs an update (of specialValues section)

**Comment by bgusach** [comment]
Hi, I guess this should either be closed or moved to the unide.java repo (unide.python already does this)

**Comment by ameinhardt** [comment]
the [testfiles in unide.java](https://github.com/eclipse/unide.java/tree/master/src/test/resources) are now validated against [the schemas](https://github.com/eclipse/unide/tree/a19c21274ff6935f5bf30042ce72e9221349cc73/ppmp/ppmp-schema/src/main/resources/org/eclipse/iot/unide/ppmp/v2). An additional automated validation would only makes sense if one of both frequently changes, which shouldn't be the case.
For a next v3 of schemas, the validation should again take place, of course
